-- =====================================================================
-- 037: Daily AI report card
--
-- Wave 3 retention/insight feature. One row per user per local-calendar
-- day, holding:
--   - descriptive: stats the dashboard renders for everyone (focus
--     minutes today, completion rate, mood from journal if present,
--     active goal pace). Cheap to compute, no AI cost.
--   - ai_suggestion: a one-line "try X tomorrow" line generated by
--     Claude. Pro-only — strengthens the Pro moat and is the most
--     prescriptive signal in the card.
--
-- Caching contract: the /api/coach/daily-card endpoint reads the row
-- for today's user-local date; if missing, it generates + writes one
-- (single AI call gated by aiQuota), then returns. Subsequent dashboard
-- opens the same day are pure DB reads. UNIQUE(user_id, date) enforces
-- the per-day singleton.
--
-- Retention: rows over 90 days old get pruned by the existing
-- retention-sweep cron (we'll add this table to its targets).
--
-- Apply via Supabase dashboard SQL editor (per HANDOFF.md gotcha #17).
-- =====================================================================

CREATE TABLE IF NOT EXISTS public.daily_cards (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id         UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  -- User-local calendar date the card describes. Always set in the
  -- user's timezone — see lib/user-date.todayKeyInTz.
  date            DATE NOT NULL,
  -- Pre-computed descriptive stats. Schema is intentionally JSONB so
  -- adding new fields (afternoon-vs-morning split, tag mix, etc.)
  -- doesn't need a migration. Today's shape:
  --   {
  --     "focus_minutes": int,
  --     "sessions_completed": int,
  --     "tasks_completed": int,
  --     "tasks_total": int,
  --     "completion_rate": number (0..1),
  --     "mood": string | null,    -- from journal_entries if present
  --     "current_streak": int,
  --     "active_goal_pct": number | null
  --   }
  descriptive     JSONB NOT NULL DEFAULT '{}'::jsonb,
  -- Pro-tier AI suggestion line. NULL for free-tier rows. Generated
  -- once per (user, date) and cached — repeat dashboard loads same day
  -- read this column instead of re-firing Claude.
  ai_suggestion   TEXT,
  -- Token cost recorded for accounting; matches the daily_anthropic_usage
  -- bucket. Useful for "how much does the daily card cost per Pro user
  -- per month?" reports without joining against a separate usage table.
  ai_tokens_used  INT NOT NULL DEFAULT 0,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (user_id, date)
);

-- Hot read pattern: "today's card for this user." The composite index
-- on (user_id, date DESC) keeps it index-only.
CREATE INDEX IF NOT EXISTS idx_daily_cards_user_date
  ON public.daily_cards(user_id, date DESC);

ALTER TABLE public.daily_cards ENABLE ROW LEVEL SECURITY;

-- Users read their own cards (powers the dashboard component).
CREATE POLICY "Users read own daily cards"
  ON public.daily_cards FOR SELECT
  USING (auth.uid() = user_id);

-- Service role writes (the /api/coach/daily-card endpoint creates
-- rows via the service-role client). No INSERT/UPDATE policy = locked
-- down to service role, matching coach_log + wa_conversation_context.

COMMENT ON TABLE public.daily_cards IS
  'One row per (user, local date). Caches descriptive stats + Pro-only AI suggestion so the dashboard renders without re-firing Claude on every open. Pruned at 90 days by retention-sweep.';
