-- =====================================================================
-- 038: Public streak shares + per-user referral coupons
--
-- Two related growth features in one migration:
--
--   (a) share_tokens — opaque 32-char tokens that map to a user_id and
--       a "kind" (only 'streak' for now). The token is the only thing
--       in the URL — never the user_id — so revocation is real and
--       guess-resistance is high. The public page at /share/streak/<token>
--       reads the token, looks up the user, computes their freeze-aware
--       streak server-side, and renders a static OG-friendly page.
--
--   (b) referrals — extend the existing `coupons` table with an optional
--       `referrer_user_id` so a coupon row can be owned by an end user
--       (not just an admin). When a referral coupon is redeemed, the
--       redeemer gets the coupon's discount AND the referrer gets a
--       kickback of `referrer_kickback_months` months on their own
--       subscription (or admin-equivalent). The kickback amount is
--       configurable per-coupon so we can run "1+1" promos by default
--       and flex into "1+2" / "2+1" later without schema work.
--
-- Why piggy-back on `coupons` rather than a parallel `referral_codes`
-- table:
--   - Coupon redemption is already idempotent + race-safe via
--     redeem_coupon_atomic (mig 011). Re-using that codepath gets
--     anti-abuse for free.
--   - The percent_off / trial_extension / free_months kinds already
--     cover the redeemer's reward shape; we just need to also reward
--     the referrer.
--   - Admins can audit referral coupons in the same dashboard listing.
--
-- Apply via Supabase dashboard SQL editor (per HANDOFF.md gotcha #17).
-- =====================================================================

-- ── 1. share_tokens ──────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.share_tokens (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id       UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  -- 32-char crypto-random string. Generated app-side via crypto.randomUUID()
  -- + base32 — the API enforces shape; we accept any text >= 16 chars to
  -- leave headroom for future schemes without migration churn.
  token         TEXT NOT NULL UNIQUE,
  kind          TEXT NOT NULL CHECK (kind IN ('streak')),
  -- NULL = active. We never DELETE rows so revoked URLs continue to
  -- short-circuit to a "this share has been revoked" page rather than
  -- silently re-mapping to a new token if the user later regenerates.
  revoked_at    TIMESTAMPTZ,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  -- One active token per (user, kind). Re-minting via the API marks the
  -- previous one revoked first, then inserts the new one — the partial
  -- index below enforces uniqueness only over active rows so the
  -- revoked history can grow.
  UNIQUE (user_id, kind, revoked_at)
);

-- Hot read: token → row, for the public /share/streak/[token] page.
-- Partial index on active rows keeps the lookup tight and lets revoked
-- history pile up without bloating the hot path.
CREATE INDEX IF NOT EXISTS idx_share_tokens_active
  ON public.share_tokens(token) WHERE revoked_at IS NULL;

ALTER TABLE public.share_tokens ENABLE ROW LEVEL SECURITY;

-- Owners read/manage their own tokens (used by the dashboard "share
-- streak" button to fetch + revoke).
DROP POLICY IF EXISTS "Users manage own share tokens" ON public.share_tokens;
CREATE POLICY "Users manage own share tokens"
  ON public.share_tokens
  FOR ALL
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- The public share page resolves token→user_id via service-role from
-- the route handler — we do NOT want anonymous SELECT here even on
-- active rows, because a leaked anon-key would let an attacker list
-- every active token. Service role bypasses RLS by default; no
-- additional policy needed.

COMMENT ON TABLE public.share_tokens IS
  'Per-user revocable share URLs. /share/streak/<token> resolves token to user_id via service-role lookup, computes streak, renders public page + OG image. One active row per (user, kind).';

-- ── 2. coupons.referrer_user_id + kickback configuration ────────────
ALTER TABLE public.coupons
  ADD COLUMN IF NOT EXISTS referrer_user_id UUID
    REFERENCES public.profiles(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS referrer_kickback_months INT
    CHECK (referrer_kickback_months IS NULL OR referrer_kickback_months > 0);

COMMENT ON COLUMN public.coupons.referrer_user_id IS
  'If set, this coupon was generated by an end user as their personal referral code. Successful redemption rewards the redeemer (per kind/discount_value) AND credits the referrer with referrer_kickback_months free months on their own subscription.';
COMMENT ON COLUMN public.coupons.referrer_kickback_months IS
  'Months of premium granted to referrer_user_id when this coupon is redeemed. NULL on non-referral coupons; required (>0) on referral rows.';

-- Lookup index for "give me this user's personal referral code".
CREATE INDEX IF NOT EXISTS idx_coupons_referrer
  ON public.coupons(referrer_user_id)
  WHERE referrer_user_id IS NOT NULL;

-- ── 3. credit_referrer_kickback RPC ─────────────────────────────────
--
-- Awards `p_months` of premium to `p_user_id` by extending their
-- subscription's current_period_end. Mirrors the free_months branch
-- in /api/coupons/redeem but in a SECURITY DEFINER function so it
-- can be called from inside the redemption flow on behalf of a
-- different user (the referrer, not the calling redeemer).
--
-- Idempotency: callers should track the (coupon_id, redemption_id) pair
-- and only call this once per redemption. The function itself is NOT
-- idempotent — calling it twice extends the subscription twice. Today
-- the only caller is /api/coupons/redeem which calls it exactly once
-- per successful redemption row.
CREATE OR REPLACE FUNCTION public.credit_referrer_kickback(
  p_user_id UUID,
  p_months  INT
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_existing      RECORD;
  v_base_ms       BIGINT;
  v_new_period    TIMESTAMPTZ;
BEGIN
  IF p_months IS NULL OR p_months <= 0 THEN
    RAISE EXCEPTION 'p_months must be > 0' USING ERRCODE = '22023';
  END IF;

  SELECT * INTO v_existing
    FROM public.subscriptions
   WHERE user_id = p_user_id
   ORDER BY created_at DESC
   LIMIT 1;

  -- Anchor the extension at max(existing period end, now). A user with
  -- a paused or cancelled sub gets the extension from "right now" rather
  -- than starting from a stale period_end in the past.
  IF v_existing.current_period_end IS NULL OR v_existing.current_period_end < now() THEN
    v_new_period := now() + (p_months || ' months')::interval;
  ELSE
    v_new_period := v_existing.current_period_end + (p_months || ' months')::interval;
  END IF;

  IF v_existing IS NULL THEN
    INSERT INTO public.subscriptions (user_id, status, current_period_end)
      VALUES (p_user_id, 'active', v_new_period);
  ELSE
    UPDATE public.subscriptions
       SET status             = 'active',
           current_period_end = v_new_period,
           cancelled_at       = NULL
     WHERE user_id = p_user_id;
  END IF;

  RETURN jsonb_build_object(
    'ok', TRUE,
    'user_id', p_user_id,
    'months_credited', p_months,
    'new_period_end', v_new_period
  );
END;
$$;

REVOKE ALL ON FUNCTION public.credit_referrer_kickback(UUID, INT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.credit_referrer_kickback(UUID, INT) TO service_role;

COMMENT ON FUNCTION public.credit_referrer_kickback IS
  'Award p_months of premium to p_user_id by extending their subscription period. Service-role-only; called from /api/coupons/redeem when a redeemed coupon has a non-null referrer_user_id.';
